# Generated by Django 5.0.7 on 2024-08-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog\\default.jpg', upload_to='blog/'),
        ),
    ]
